swagger: "2.0"
info:
  title: bnb-hotel-management
  description: "Get the name of an airport from its three-letter IATA code."
  version: "1.0.0"
schemes:
  - "https"
paths:
  "/notifications":
    get:
      description: "Get user's notifications"
      operationId: "get_user_notifications"
      parameters:
        - in: query
          name: user_id
          required: true
          type: string
          minimum: 1
          description: user id.
      x-google-backend:
        address: "https://us-central1-serverless-bnb.cloudfunctions.net/notification-management"
        path_translation: [APPEND_PATH_TO_ADDRESS]
      responses:
        200:
          description: "Success."
          schema:
            type: "object"
        400:
          description: "Error"