"""
    @author Bharatwaaj Shankaranarayanan
    @application hotel-score-model
    @description This application takes the customer reviews as input and gives a rating to a particular hotel
    @version 1.0.0
"""
# Imports
from google.cloud import language_v1

class HoteScoreModel():
    
    """
        @author Bharatwaaj Shankaranarayanan
        @class HotelScoreModel
        @description HotelScoreModel Generic class
        @params
        @return Object
    """
    
    # Constructor for the HotelScoreModel
    def __init__(self):
        
        # Creating the Language Service Client
        self.client = language_v1.LanguageServiceClient()
        
    def analyze(self, data):
        
        """
            @author Bharatwaaj Shankaranarayanan
            @function analyze
            @description This function analyzes the data and provides the sentiment results from GCP Cloud Natural Language API
            @params data (str)
            @returns annotations (AnalyzeSentimentResponse)
        """
        
        # Create the content document from the set of input sentences
        document = language_v1.Document(content=data,type_=language_v1.Document.Type.PLAIN_TEXT)
        
        # Get the annotations of the document from GCP Natural Language API client
        annotations = self.client.analyze_sentiment(request={"document": document})
        
        return annotations
    
    def generate_rating_score(self, annotations):
        """
            @author Bharatwaaj Shankaranarayanan
            @function generate_rating_score
            @description This function parses the annotations for the data generated by the GCP Natural Language API and generates the score
            @params annotations (AnalyzeSentimentResponse)
            @returns score (float)
        """
        return ((annotations.document_sentiment.score + 1) * 5) / 2
    
    def generate_rating_polarity(self, annotations):
        """
            @author Bharatwaaj Shankaranarayanan
            @function generate_rating_polarity
            @description This function parses the annotations for the data generated by the GCP Natural Language API and generates rating polity
            @params annotations (AnalyzeSentimentResponse)
            @returns polarity (enum)
        """
        if(annotations.document_sentiment.score < 0):
            return "NEGATIVE";
        elif (annotations.document_sentiment.score == 0):
            return "NEUTRAL";
        else:
            return "POSITIVE";